using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using InventoryBrother.Domain.Common;

namespace InventoryBrother.Infrastructure.Data.Entities;

public class JournalEntry : BaseEntity
{
    [Key]
    public long Id { get; set; }

    public DateTime Date { get; set; }
    
    [MaxLength(50)]
    public string? ReferenceNumber { get; set; } // e.g., INV-001, PO-005
    
    [MaxLength(255)]
    public string? Description { get; set; } // Memo

    public bool IsAutoPosted { get; set; } // True if generated by system (Sales/Purchases)

    // Navigation
    public virtual ICollection<JournalEntryLine> Lines { get; set; } = new List<JournalEntryLine>();
}
