'use server'

import { db } from "@/lib/db"
import { suppliers, NewSupplier } from "@/db/schema"
import { revalidatePath } from "next/cache"
import { eq, desc } from "drizzle-orm"

export async function getSuppliers() {
  return await db.select().from(suppliers).orderBy(desc(suppliers.createdAt))
}

export async function createSupplier(formData: FormData) {
  const data: NewSupplier = {
    // id autogenerated
    name: formData.get("name") as string,
    contactPerson: formData.get("contactPerson") as string,
    email: formData.get("email") as string,
    mobile: formData.get("mobile") as string,
    address: formData.get("address") as string,
    status: "Active",
    openingBalance: parseFloat(formData.get("openingBalance") as string || "0"),
  }
  
  await db.insert(suppliers).values(data)
  revalidatePath("/inventory/suppliers")
}

export async function deleteSupplier(id: string) {
  await db.delete(suppliers).where(eq(suppliers.id, id))
  revalidatePath("/inventory/suppliers")
}
