CREATE TABLE `products` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`description` text,
	`barcode` text,
	`barcode_type` text,
	`price` integer DEFAULT 0,
	`sale_price` integer,
	`mrp` integer,
	`cost` integer,
	`category_id` integer,
	`unit_id` integer,
	`brand_id` integer,
	`stock_quantity` integer DEFAULT 0,
	`min_stock` integer DEFAULT 0,
	`image` text,
	`created_at` integer DEFAULT (strftime('%s', 'now')),
	`updated_at` integer,
	`created_by` text,
	`updated_by` text,
	`store_id` integer DEFAULT 1,
	FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`unit_id`) REFERENCES `units`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`brand_id`) REFERENCES `brands`(`id`) ON UPDATE no action ON DELETE no action
);
