//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8922
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock_System.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stock_System.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _03 {
            get {
                object obj = ResourceManager.GetObject("03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _21 {
            get {
                object obj = ResourceManager.GetObject("21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _35 {
            get {
                object obj = ResourceManager.GetObject("35", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _4 {
            get {
                object obj = ResourceManager.GetObject("4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _41 {
            get {
                object obj = ResourceManager.GetObject("41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _81b9691e2de3c2ef0a2459b4f6146541__app_login_web_forms {
            get {
                object obj = ResourceManager.GetObject("81b9691e2de3c2ef0a2459b4f6146541--app-login-web-forms", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap a084848f4e6e545b9e7b16d102b6f866_colorful_abstract_background {
            get {
                object obj = ResourceManager.GetObject("a084848f4e6e545b9e7b16d102b6f866-colorful-abstract-background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ACTS {
            get {
                object obj = ResourceManager.GetObject("ACTS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Afghan_Contemporary_Technology {
            get {
                object obj = ResourceManager.GetObject("Afghan Contemporary Technology", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGENDA {
            get {
                object obj = ResourceManager.GetObject("AGENDA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap archeologist_128_hot {
            get {
                object obj = ResourceManager.GetObject("archeologist_128_hot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArreterSZ {
            get {
                object obj = ResourceManager.GetObject("ArreterSZ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AVX_ICONS_USERS_FOLDER {
            get {
                object obj = ResourceManager.GetObject("AVX_ICONS USERS FOLDER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap backup_data_icon {
            get {
                object obj = ResourceManager.GetObject("backup_data-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap backup_icon {
            get {
                object obj = ResourceManager.GetObject("backup_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cadenas_3D {
            get {
                object obj = ResourceManager.GetObject("Cadenas 3D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap canstock0349683 {
            get {
                object obj = ResourceManager.GetObject("canstock0349683", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap coins {
            get {
                object obj = ResourceManager.GetObject("coins", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DUOTANG_ESSENTIALS_ICON_PP09 {
            get {
                object obj = ResourceManager.GetObject("DUOTANG ESSENTIALS ICON PP09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap engineered_garments_fw2009_tab_shirts {
            get {
                object obj = ResourceManager.GetObject("engineered_garments_fw2009_tab_shirts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap erasoft_logo {
            get {
                object obj = ResourceManager.GetObject("erasoft_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Eternal_Blue_doc {
            get {
                object obj = ResourceManager.GetObject("Eternal Blue doc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Eternal_Blue_rar {
            get {
                object obj = ResourceManager.GetObject("Eternal Blue rar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Flat_for_PC_Edit_Text_ico_128x128 {
            get {
                object obj = ResourceManager.GetObject("Flat_for_PC-Edit_Text.ico-128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Guide_ATS_image00 {
            get {
                object obj = ResourceManager.GetObject("Guide-ATS-image00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HEINS_QUANTUM_FOLDERS_TEXT_APPS {
            get {
                object obj = ResourceManager.GetObject("HEINS_QUANTUM_FOLDERS TEXT APPS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HelpResource_ashx {
            get {
                object obj = ResourceManager.GetObject("HelpResource.ashx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap iCandy_Junior_006 {
            get {
                object obj = ResourceManager.GetObject("iCandy_Junior 006", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconsLandVistaElementsIconsDemo_PNG_128x128_Search2_png_128x128 {
            get {
                object obj = ResourceManager.GetObject("IconsLandVistaElementsIconsDemo-PNG-128x128-Search2.png-128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap image {
            get {
                object obj = ResourceManager.GetObject("image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap image2 {
            get {
                object obj = ResourceManager.GetObject("image2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap images {
            get {
                object obj = ResourceManager.GetObject("images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ino6 {
            get {
                object obj = ResourceManager.GetObject("ino6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap invoi5 {
            get {
                object obj = ResourceManager.GetObject("invoi5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap invoice_icon42 {
            get {
                object obj = ResourceManager.GetObject("invoice_icon42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap invoice2 {
            get {
                object obj = ResourceManager.GetObject("invoice2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap k1327051 {
            get {
                object obj = ResourceManager.GetObject("k1327051", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap k1575014 {
            get {
                object obj = ResourceManager.GetObject("k1575014", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Lock {
            get {
                object obj = ResourceManager.GetObject("Lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logimage {
            get {
                object obj = ResourceManager.GetObject("logimage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap login_icon {
            get {
                object obj = ResourceManager.GetObject("login_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap login_icon1 {
            get {
                object obj = ResourceManager.GetObject("login_icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mateen {
            get {
                object obj = ResourceManager.GetObject("mateen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Messenger_Icons_8 {
            get {
                object obj = ResourceManager.GetObject("Messenger Icons 8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mglass {
            get {
                object obj = ResourceManager.GetObject("mglass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NetByte_Design_Studio___0019 {
            get {
                object obj = ResourceManager.GetObject("NetByte Design Studio - 0019", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NetByte_Design_Studio___0063 {
            get {
                object obj = ResourceManager.GetObject("NetByte Design Studio - 0063", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NetByte_Design_Studio___0134 {
            get {
                object obj = ResourceManager.GetObject("NetByte Design Studio - 0134", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NetByte_Design_Studio___0143 {
            get {
                object obj = ResourceManager.GetObject("NetByte Design Studio - 0143", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NetByte_Design_Studio___0155 {
            get {
                object obj = ResourceManager.GetObject("NetByte Design Studio - 0155", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NetByte_Design_Studio___01551 {
            get {
                object obj = ResourceManager.GetObject("NetByte Design Studio - 01551", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NetByte_Design_Studio___0294 {
            get {
                object obj = ResourceManager.GetObject("NetByte Design Studio - 0294", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NetByte_Design_Studio___0365 {
            get {
                object obj = ResourceManager.GetObject("NetByte Design Studio - 0365", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NetByte_Design_Studio___0468 {
            get {
                object obj = ResourceManager.GetObject("NetByte Design Studio - 0468", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NetByte_Design_Studio___0473 {
            get {
                object obj = ResourceManager.GetObject("NetByte Design Studio - 0473", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NetByte_Design_Studio___0738 {
            get {
                object obj = ResourceManager.GetObject("NetByte Design Studio - 0738", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NetByte_Design_Studio___0749 {
            get {
                object obj = ResourceManager.GetObject("NetByte Design Studio - 0749", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NetByte_Design_Studio___1132 {
            get {
                object obj = ResourceManager.GetObject("NetByte Design Studio - 1132", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NetByte_Design_Studio___1352 {
            get {
                object obj = ResourceManager.GetObject("NetByte Design Studio - 1352", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NetByte_Design_Studio___1423 {
            get {
                object obj = ResourceManager.GetObject("NetByte Design Studio - 1423", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap new_logo {
            get {
                object obj = ResourceManager.GetObject("new logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap newlogo {
            get {
                object obj = ResourceManager.GetObject("newlogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pastel_Icons_printer_ico_128x128 {
            get {
                object obj = ResourceManager.GetObject("Pastel_Icons-printer.ico-128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PNG_Folders_Printer_Folder_png_256x256 {
            get {
                object obj = ResourceManager.GetObject("PNG-Folders-Printer_Folder.png-256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PNG_Hardware_Search_Drive_png_256x256 {
            get {
                object obj = ResourceManager.GetObject("PNG-Hardware-Search_Drive.png-256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PNG_Other_Padlock_User_1Control_png_256x256 {
            get {
                object obj = ResourceManager.GetObject("PNG-Other-Padlock_User_1Control.png-256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PNG_Start_Menu_Search_png_256x256 {
            get {
                object obj = ResourceManager.GetObject("PNG-Start_Menu-Search.png-256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polaris_Logo {
            get {
                object obj = ResourceManager.GetObject("Polaris-Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polaris_Logo1 {
            get {
                object obj = ResourceManager.GetObject("Polaris-Logo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polaris_Logo2 {
            get {
                object obj = ResourceManager.GetObject("Polaris-Logo2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polaris_Logo3 {
            get {
                object obj = ResourceManager.GetObject("Polaris-Logo3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polaris_Logo4 {
            get {
                object obj = ResourceManager.GetObject("Polaris-Logo4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Polaris_Logo5 {
            get {
                object obj = ResourceManager.GetObject("Polaris-Logo5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sale_2 {
            get {
                object obj = ResourceManager.GetObject("sale 2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sbLogo {
            get {
                object obj = ResourceManager.GetObject("sbLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stock_photo_a_woman_calculation_all_the_bills_she_have_using_a_calculator_27337132 {
            get {
                object obj = ResourceManager.GetObject("stock-photo-a-woman-calculation-all-the-bills-she-have-using-a-calculator-2733713" +
                        "2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stock_photo_man_paying_bills_online_35124256 {
            get {
                object obj = ResourceManager.GetObject("stock-photo-man-paying-bills-online-35124256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stock_photo_money_32890786 {
            get {
                object obj = ResourceManager.GetObject("stock-photo-money-32890786", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stock_photo_time_for_book_keeping_619506 {
            get {
                object obj = ResourceManager.GetObject("stock-photo-time-for-book-keeping-619506", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Summary {
            get {
                object obj = ResourceManager.GetObject("Summary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wse {
            get {
                object obj = ResourceManager.GetObject("wse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
